config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  get "/help", to: "static_pages#help"
  get "/about", to: "static_pages#about"
  get "/contact", to: "static_pages#contact"
  get "/search", to: "static_pages#search"
  get "/admin", to: "static_pages#admin"
  get "/load_statistics", to: "static_pages#load_statistics"
  devise_for :users, :controllers => { :omniauth_callbacks => "user/omniauth_callbacks" }
  devise_scope :user do
    get "/sign_in", to: "devise/sessions#new"
    delete "/sign_out", to: "devise/sessions#destroy"
  end
  resources :users, except: :new do
    member do
      get :following, :followers
    end
  end
  resources :relationships, only: [:create, :destroy]
  resources :posts
  resources :comments
  resources :likes, only: [:create, :destroy]
  resources :tags, only: :show
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :user, presence: true
  validates :post, presence: true
  validates :content, presence: true,
    length: {maximum: Settings.comment.content.max_length}
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :logged_in_user, only: [:create, :update, :destroy]
  before_action :load_comment, only: [:edit, :update, :destroy]

  def create
    @comment = current_user.comments.build comment_params
    if @comment.save
      render json: {
        status: :success,
        html: render_to_string(partial: "comments/comment", locals: {comment: @comment}, layout: false),
        comment_number: @comment.post.comments.size.to_s <<
          " comment".pluralize(@comment.post.comments.size)
      }
    else
      @feed_items = []
      render "static_pages/home"
    end
  end

  def show
    @comment = comment.find_by id: params[:id]
  end

  def edit
    render json: {
      status: :success,
      html: render_to_string(partial: "comments/edit_form", locals: {comment: @comment}, layout: false)
    }
  end

  def update
    if @comment.update_attributes comment_params
      render json: {
        status: :success,
        html: render_to_string(partial: "comments/comment", locals: {comment: @comment}, layout: false)
      }
    else
      render json: {
        status: :error,
        message: "ERROR"
      }
    end
  end

  def destroy
    if @comment.destroy
      render json: {
        status: :success,
        comment_number: @comment.post.comments.size.to_s <<
          " comment".pluralize(@comment.post.comments.size)
      }
    else
      render json: {status: :error}
    end
  end

  private

  def comment_params
    params.require(:comment).permit :content, :post_id
  end

  def load_comment
    @comment = Comment.find_by id: params[:id]
    redirect_to root_url if @comment.nil?
  end
end

app/views/comments/_comment.html.erb
<div class="comment" id="<%= "comment-" << comment.id.to_s %>">
  <%= link_to gravatar_for(comment.user, Settings.user.gravatar.size_40), comment.user %>
  <span class="user"><%= link_to comment.user.name, comment.user %></span>
  <span class="content"><%= comment.content %></span>
  <span class="timestamp">
    <%= t ".posted" %> <%= time_ago_in_words comment.created_at %>
  </span>
  <% if user_signed_in? %>
    <% if comment.user.is_user? current_user or current_user.is_admin? %>
    <div class="dropdown delete">
      <button class="btn dropdown-toggle btn-dropdown" type="button" data-toggle="dropdown">
        <span class="caret"></span></button>
        <ul class="dropdown-menu dropdown-menu-right">
          <li>
            <%= link_to t(".edit"), edit_comment_path(comment.id) %>
          </li>
          <li>
            <%= link_to t(".delete"), comment, method: :delete,
            data: {confirm: t(".you_sure")}%>
          </li>
        </ul>
      </div>
    <% end %>
  <% end %>
</div>

app/views/comments/_edit_form.html.erb
<%= form_for @comment, html: {class: "update-comment"}, data: {id: @comment.id} do |f| %>
  <%= render "shared/error_messages", object: f.object %>
  <span class="field frm-comment">
    <%= gravatar_for current_user, 32 %>
    <%= f.text_field :content, placeholder: t(".placeholder"),
      class: "txt-comment", id: "txt-comment-" << @comment.post_id.to_s %>
  </span>
  <%= f.hidden_field :post_id %>
  <%= f.submit t(".comment"), class: "btn btn-primary hidden" %>
<% end %>