config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  get "/help", to: "static_pages#help"
  get "/about", to: "static_pages#about"
  get "/contact", to: "static_pages#contact"
  get "/search", to: "static_pages#search"
  get "/admin", to: "static_pages#admin"
  get "/load_statistics", to: "static_pages#load_statistics"
  devise_for :users, :controllers => { :omniauth_callbacks => "user/omniauth_callbacks" }
  devise_scope :user do
    get "/sign_in", to: "devise/sessions#new"
    delete "/sign_out", to: "devise/sessions#destroy"
  end
  resources :users, except: :new do
    member do
      get :following, :followers
    end
  end
  resources :relationships, only: [:create, :destroy]
  resources :posts
  resources :comments
  resources :likes, only: [:create, :destroy]
  resources :tags, only: :show
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :post_tags
  has_many :tags, through: :post_tags

  scope :post_sort, ->{order created_at: :desc}

  validates :title, presence: true,
    length: {maximum: Settings.post.title.max_length}
  validates :user, presence: true
  validates :content, presence: true,
    length: {maximum: Settings.post.content.max_length}
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :logged_in_user, only: [:create, :destroy]
  before_action :load_post, only: [:edit, :update, :destroy]
  before_action :verify_admin!, only: :destroy

  def create
    @post = current_user.posts.build post_params

    if @post.save
      tags = params[:tags]
      tags.split(",").each do |tag_name|
        tag = Tag.find_by(name: tag_name)

        if tag.nil?
          @post.tags.create name: tag_name
        else
          @post.post_tags.create tag_id: tag.id
        end
      end

      render json: {
        status: :success,
        html: render_to_string(partial: "posts/post", locals: {post: @post}, layout: false),
        placeholder: "Input tags here"
      }
    else
      @feed_items = []
      render "static_pages/home"
    end
  end

  def show
    @post = Post.find_by id: params[:id]
  end

  def edit
    render json: {
      status: :success,
      html: render_to_string(partial: "posts/edit_form", locals: {post: @post}, layout: false)
    }
  end

  def update
    if @post.update_attributes post_params
      render json: {
        status: :success,
        html: render_to_string(partial: "posts/post", locals: {post: @post}, layout: false)
      }
    else
      render json: {
        status: :error
      }
    end
  end

  def destroy
    if @post.destroy
      render json: {status: :success}
    else
      render json: {status: :error}
    end
  end

  private

  def post_params
    params.require(:post).permit :content, :picture, :title
  end

  def load_post
    @post = Post.find_by id: params[:id]
    redirect_to root_url if @post.nil?
  end

  def verify_admin!
    redirect_to root_url unless current_user.is_admin?
  end
end

app/views/posts/_edit_form.html.erb
  <div class="modal fade" id="myModal" role="dialog">
    <div class="modal-dialog">

      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title">Edit post</h4>
        </div>
        <div class="modal-body">
          <% @post ||= post %>
          <li class="post">
            <%= link_to gravatar_for(@post.user, 50), @post.user %>
            <span class="user"><%= link_to @post.user.name, @post.user %></span>

            <%= form_for @post, data: {id: @post.id} do |f| %>
              <%= render "shared/error_messages", object: f.object %>

              <div class="form-group">
                <%= f.text_field :title, placeholder: t(".placeholder_title"), class: "txt-post form-control" %>
              </div>
              <div class="form-group">
                <%= f.text_area :content, placeholder: t(".placeholder_content"), class: "txt-post form-control" %>
              </div>
              <%= f.submit t(".post"), class: "btn btn-primary", id: "update-post" %>
            <% end %>
          </li>

        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
      </div>

    </div>
  </div>

app/views/posts/_post.html.erb
<% post ||= @post %>
<li class="post" id="post-<%= post.id %>">
  <%= link_to gravatar_for(post.user, 50), post.user %>
  <span class="user"><%= link_to post.user.name, post.user %></span>
  <span class="timestamp">
    <%= t ".posted" %> <%= time_ago_in_words post.created_at %>
    <%= t ".ago" %>.<br>

    <% post.tags.each do |tag| %>
    <%= link_to tag do %>
    <span class="label label-primary"><%= tag.name %></span>
    <% end %>
    <% end %>
  </span>
  <span class="title">
    <%= link_to post.title, post %>
  </span>
  <div class="content">
    <%= post.content %>
    <%= image_tag post.picture.url if post.picture? %>
  </div>

  <%= render "posts/post_action", post: post %>

  <% if user_signed_in? %>
  <% if post.user.is_user? current_user or current_user.is_admin? %>
  <div class="dropdown delete">
    <button class="btn dropdown-toggle btn-dropdown" type="button" data-toggle="dropdown">
      <span class="caret"></span></button>
      <ul class="dropdown-menu dropdown-menu-right">
        <li>
          <a class="edit-post" id="<%= post.id %>">edit</a>
        </li>
        <li>
          <a class="delete-post" id="<%= post.id %>">delete</a>
        </li>
      </ul>
    </div>
    <% end %>
    <% end %>

    <div class="comment-area">
      <div class="post-comment" id="<%= "post-comment-" << post.id.to_s %>">
        <% if post.comments.any? %>
        <% @comments = post.comments %>
        <%= render @comments %>
        <% end %>
      </div>

      <% if user_signed_in? %>
      <% @comment = current_user.comments.build user_id: current_user.id, post_id: post.id %>
      <%= render "shared/comment_form" %>
      <% end %>
    </div>
  </li>

app/views/posts/_post_action.html.erb
<span class="info">
  <span id="like-number-<%= post.id %>" class="like-number">
    <%= post.likes.size %>
    <%= "like".pluralize post.likes.size %>
  </span>
  <span id="comment-number-<%= post.id %>">
    <%= post.comments.size %>
    <%= "comment".pluralize post.comments.size %>
  </span>
</span>
<div class="post-action">
  <% if current_user.liked? post %>
  <span class="delete-like" data-id="<%= post.id %>" id="like-<%= post.id %>">
    <span class="glyphicon glyphicon-thumbs-up"></span> Like
  </span>
  <% else %>
  <span class="like" data-id="<%= post.id %>" id="like-<%= post.id %>">
    <span class="glyphicon glyphicon-thumbs-up"></span> Like
  </span>
  <% end %>
  <span class="show-comment">Comment</span>
  <span class="dropdown">
    <span class="dropdown-toggle" data-toggle="dropdown">Share</span>
    <ul class="dropdown-menu">
      <%= social_share_button_tag(post.title, url: post_url(post)) %>
    </ul>
  </span>
</div>

app/views/posts/show.html.erb
<div class="row">
  <div class="col-md-8">
    <ol class="posts" id="posts">
      <%= render @post %>
    </ol>
  </div>
</div>