config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  get "/help", to: "static_pages#help"
  get "/about", to: "static_pages#about"
  get "/contact", to: "static_pages#contact"
  get "/search", to: "static_pages#search"
  get "/admin", to: "static_pages#admin"
  get "/load_statistics", to: "static_pages#load_statistics"
  devise_for :users, :controllers => { :omniauth_callbacks => "user/omniauth_callbacks" }
  devise_scope :user do
    get "/sign_in", to: "devise/sessions#new"
    delete "/sign_out", to: "devise/sessions#destroy"
  end
  resources :users, except: :new do
    member do
      get :following, :followers
    end
  end
  resources :relationships, only: [:create, :destroy]
  resources :posts
  resources :comments
  resources :likes, only: [:create, :destroy]
  resources :tags, only: :show
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <strong>
    &copy; <%= Time.zone.now.year %>. <%= t ".all_right" %>.
  <strong>
    <ul>
      <li><%= link_to t(".about"), about_path %></li>
      <li><%= link_to t(".contact"), contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
  <div class="container">
    <nav>
      <%= link_to t("app_name"), root_path, class: "logo" %>
      <% if user_signed_in? %>
        <%= form_tag search_path, method: :post, class: "navbar-form navbar-left form-inline" do %>
          <div class="form-group">
            <%= text_field_tag :search, params[:search], placeholder: t(".search_placeholder"),
              class: "search-form form-control input-sm" %>
          </div>
          <%= submit_tag t(".search"), class: "btn hidden" %>
        <% end %>
      <% end %>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><%= link_to t(".profile"), current_user %></li>
          <li><%= link_to t(".users"), "#" %></li>
          <li><%= link_to t(".help"), help_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <%= t ".account" %> <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to t(".settings"), edit_user_registration_path %></li>
              <li class="divider"></li>
              <li>
                <%= link_to t(".sign_out"), sign_out_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to t(".users"), "#" %></li>
          <li><%= link_to t(".help"), help_path %></li>
          <li><%= link_to t(".log_in"), sign_in_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title yield(:title) %></title>
    <%= favicon_link_tag "icon.ico" %>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag "application", media: "all",
      "data-turbolinks-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbolinks-track": "reload" %>
  </head>
  <body>
    <%= render "layouts/header" %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render "layouts/footer" %>
    </div>
  </body>
</html>